{"uuid": "0c5c7bea-80f7-4064-84a9-5b1ce65fb85a", "befores": [{"name": "xunit_setup_class_fixture_Test", "status": "broken", "statusDetails": {"message": "KeyError: 'data'\n", "trace": "  File \"D:\\Pyproject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Pyproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Pyproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Pyproject\\venv\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\Pyproject\\venv\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\Pyproject\\frame\\pytest_frame\\main_interface.py\", line 11, in setup_class\n    self.s, self.headers = self.session_login()\n  File \"D:\\Pyproject\\frame\\pytest_frame\\main_interface.py\", line 23, in session_login\n    _token = _resp.json()['data']['accessToken']\n"}, "start": 1642837268159, "stop": 1642837268640}], "start": 1642837268159, "stop": 1642837268909}